spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xa
    username: xa
    password: xa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

server:
  port: 8080
